version: '3.8'

services:
  frontend:
    image: kora-frontend
    container_name: zucalweb
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    networks:
      - zucal-network

  backend:
    image: kora-backend
    container_name: zucal-backend
    build:
      context: ./backend-kora
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3001:3001"
    env_file:
      - ./backend-kora/.env
    networks:
      - zucal-network

networks:
  zucal-network:
    external: true