post https://zucal-backend-v1-0.onrender.com/api/user/2
content-type: application/json
###
POST https://convert-input-api-latest.onrender.com/api/parse-input
Content-Type: application/json

{
    "input": "Call with Lisa next monday at 9am,today is 2025-04-12, timezone is GMT+7",
    "organizer": 2
}
###
POST https://zucal-backend-v1-0.onrender.com/api/booking/parse-input
Content-Type: application/json

{
    "input": "Call with Lisa next monday at 9am,today is 2025-04-12, timezone is GMT+7",
    "organizer": 2
}