GET http://localhost:3004/api/user/2
content-type: application/json
###
POST http://localhost:3004/api/booking/parse-input
Content-Type: application/json

{
    "input": "Call with Lisa next monday at 9am,today is 2025-04-12, timezone is GMT+7",
    "organizer": 2
}
